name = "TextSpace"
uuid = "96538882-321b-4ccb-9f4b-e34e7d43c35c"
authors = ["Alexander V. Mantzaris", "Samira Jahangiri"]
version = "1.0.0-DEV"

[deps]
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
Unicode = "1.11.0"
julia = ">=1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
